name: Plastic4trade
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  retrofit: any
  dio: any
  charts_flutter: any
  provider: any
  fluttertoast: any
  shared_preferences: any
  flutter_otp_text_field: ^1.1.1
  file_picker: ^5.2.7
  url_launcher: ^6.0.10

  intl: any
  flutter_slidable: any
  pointer_interceptor: any
  youtube_player_flutter: any
  image_picker: ^0.8.9
  flutter_google_places_hoc081098: ^1.0.0-nullsafety.5
  google_api_headers: ^1.1.1
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_maps_flutter: ^2.1.1
  connectivity_plus: any
  flutter_image_compress: any
#  webview_flutter: any
  share: any
  path_provider: ^2.0.15
  package_info_plus: any
  flutter_html: any
  flutter_typeahead: any
  google_maps_flutter_ios: ^2.2.3
  firebase_messaging: any
  firebase_core: any
  flutter_local_notifications: ^9.3.2
  firebase_core_platform_interface: any
  firebase_auth: any
  flutter_firebase_chat_core: any
  flutter_pdfview: ^1.3.1

  cloud_firestore: any
  device_info_plus: any
  country_calling_code_picker: ^2.0.1
  android_id : any
  syncfusion_flutter_charts: any
  firebase_storage: any
  cached_network_image: ^3.2.3
  shared_value: ^3.0.0
  firebase_database: any
  photo_view : any
  responsive_grid_list: ^1.3.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  getwidget: any
  marquee: ^2.2.3
  email_validator: any
  flutter_rating_bar: any
  youtube_player_iframe: ^4.0.4
  badges: ^3.0.2
  http: any
  slide_switcher: ^1.1.2
  image_cropper: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/plastic4trade logo final.png
      - assets/plastic4trade logo final 1 (2).png
      - assets/image 1.png
      - assets/image 2.png
      - assets/Vector.png
      - assets/Ellipse 1.png
      - assets/Ellipse 6.png
      - assets/Vector (1).png
      - assets/Notification.png
      - assets/homemsg.png
      - assets/Home.png
      - assets/sale.png
      - assets/Buyer.png
      - assets/more.png
      - assets/news.png
      - assets/register_title.png
      - assets/back.png
      - assets/homegrid.png
      - assets/homeslider.png
      - assets/search.png
      - assets/location.png
      - assets/homefiltter.png
      - assets/image 3.png
      - assets/like.png
      - assets/Send.png
      - assets/price.png
      - assets/hidepassword.png
      - assets/homeprice.png
      - assets/Ellipse 13.png
      - assets/bag-2.png
      - assets/clipboard-text.png
      - assets/directbox-default.png
      - assets/document-text.png
      - assets/play-circle.png
      - assets/forward.png
      - assets/box.png
      - assets/shop.png
      - assets/shopping-cart.png
      - assets/video.png
      - assets/bag-tick.png
      - assets/heart-circle.png
      - assets/profile-2user.png
      - assets/star.png
      - assets/premium_mem.png
      - assets/award.png
      - assets/send-2.png
      - assets/whatsapp.png
      - assets/youtube.png
      - assets/Telegram.png
      - assets/Twitter.png
      - assets/instagram.png
      - assets/linkdin.png
      - assets/LinkedIn.png
      - assets/facebook.png
      - assets/Facebook (1).png
      - assets/YouTube (1).png
      - assets/Twitter.png
      - assets/edit.png
      - assets/edit1.png
      - assets/user.png
      - assets/call.png
      - assets/verify.png
      - assets/sms.png
      - assets/follwe.png
      - assets/star.png
      - assets/hori_line.png
      - assets/add_document.png
      - assets/flag.png
      - assets/password.png
      - assets/forgetPassword.png
      - assets/Otpverification.png
      - assets/flash.png
      - assets/Delete.png
      - assets/delete.png
      - assets/addphoto.png
      - assets/addphoto1.png
      - assets/fav.png
      - assets/call1.png
      - assets/contactus_back.png
      - assets/contactus_loc.png
      - assets/msg1.png
      - assets/delete1.png
      - assets/delete2.png
      - assets/Setting.png
      - assets/PaidPost.png
      - assets/Play.png
      - assets/buyer_seller_detail.png
      - assets/like1.png
      - assets/send2.png
      - assets/view1.png
      - assets/call1.png
      - assets/user_chat.png
      - assets/follow1.png
      - assets/floating.png
      - assets/floating_back.png
      - assets/call2.png
      - assets/web.png
      - assets/verify1.png
      - assets/trust.png
      - assets/Premium1.png
      - assets/Premium2.png
      - assets/add_image.png
      - assets/add_doc.png
      - assets/pdf_file_icon.png
      - assets/share1.png
      - assets/graph.png
      - assets/list_data.png
      - assets/diagram.png
      - assets/show.png
      - assets/bussines_profile.png
      - assets/Line.png
      - assets/round.png
      - assets/account.png

  fonts:
        - family: Metropolis
          fonts:
            - asset: assets/fonst/Metropolis-Regular.otf
            - asset: assets/fonst/Metropolis-Black.otf
            - asset: assets/fonst/Metropolis-SemiBold.otf
